/*
 * sim_hardware.c
 *
 * Simulation back-end for execute_flight_autosequence().
 * Replaces every hardware/RTOS call with CSV-driven equivalents so the
 * autosequence logic can run on a host PC without modification.
 *
 * CSV format (generated by generate_flight_data.py):
 *   timestamp_ms,
 *   bar1_hPa, bar2_hPa,
 *   bar1_temp_C, bar2_temp_C,
 *   imu1_XL_x, imu1_XL_y, imu1_XL_z, imu1_W_x, imu1_W_y, imu1_W_z,
 *   imu2_XL_x, imu2_XL_y, imu2_XL_z, imu2_W_x, imu2_W_y, imu2_W_z
 *
 * Each row corresponds to one 20 ms sample-period tick.
 * Simulated time is taken directly from the timestamp_ms column so that
 * getTime() / time_since() match the CSV timeline exactly.
 *
 * ONLY the functions declared in sim_hardware.h are defined here.
 * All physics / detection logic in ad-functions.c is untouched.
 */

#include "sim_hardware.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ═══════════════════════════════════════════════════════════════════════════
 * Fluctus timing constants  (milliseconds after ignition)
 * These are computed by generate_flight_data.py to match the CSV profile.
 * ═══════════════════════════════════════════════════════════════════════════ */
#define FLUCTUS_APOGEE_FLIGHT_MS   61071U   /* ~60.6 s after ignition (apogee) */
#define FLUCTUS_5K_FLIGHT_MS      246898U   /* ~246.4 s – below 5 000 ft       */
#define FLUCTUS_1K_FLIGHT_MS      295658U   /* ~295.2 s – below 1 000 ft       */

/* Absolute sim-time (ms) at which the valves open and ignition_timestamp
 * is captured by the autosequence.  Must match the CSV: first row whose
 * timestamp_ms >= this value triggers valves_open() → 1.              */
#define VALVES_OPEN_SIM_MS        500U

/* ═══════════════════════════════════════════════════════════════════════════
 * Internal state  (all static – hidden from the rest of the build)
 * ═══════════════════════════════════════════════════════════════════════════ */
static FILE    *s_csv          = NULL;
static int      s_csv_ready    = 0;

static uint32_t s_sim_time_ms  = 0;   /* current simulated time             */
static uint32_t s_ignition_ms  = 0;   /* absolute sim-time of ignition      */
static int      s_ignited       = 0;   /* 1 after valves first opened        */

/* Last row read – used so every sensor getter sees consistent data within
 * one loop iteration even if called multiple times.                     */
static struct {
    float bar1, bar2;
    float bt1,  bt2;
    float xl1_x, xl1_y, xl1_z, w1_x, w1_y, w1_z;
    float xl2_x, xl2_y, xl2_z, w2_x, w2_y, w2_z;
} s_row;

/* Deployment one-shot guards */
static int s_pilot_fired   = 0;
static int s_drogue_fired  = 0;
static int s_main_fired    = 0;

/* ═══════════════════════════════════════════════════════════════════════════
 * CSV initialisation  (called lazily on first get_sensor_data)
 * ═══════════════════════════════════════════════════════════════════════════ */
static void csv_init(void)
{
    if (s_csv_ready) return;

    s_csv = fopen(SIM_CSV_FILE, "r");
    if (!s_csv) {
        fprintf(stderr, "[SIM] ERROR: cannot open '%s'\n", SIM_CSV_FILE);
        exit(EXIT_FAILURE);
    }

    /* Skip header line */
    char buf[512];
    if (!fgets(buf, sizeof(buf), s_csv)) {
        fprintf(stderr, "[SIM] ERROR: CSV is empty\n");
        exit(EXIT_FAILURE);
    }

    s_csv_ready = 1;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Time
 * ═══════════════════════════════════════════════════════════════════════════ */
uint32_t getTime(void)
{
    return s_sim_time_ms;
}

uint32_t time_since(uint32_t timestamp)
{
    /* Unsigned subtraction handles the wrap-around the same way embedded code
     * would on a 32-bit millisecond counter.                               */
    return s_sim_time_ms - timestamp;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Sensor data  – reads one CSV row per call, advances the clock
 * ═══════════════════════════════════════════════════════════════════════════ */
void get_sensor_data(float *bar1_hPa, float *bar2_hPa,
                     IMU_values *imu1, IMU_values *imu2,
                     float *bar1_temp_C, float *bar2_temp_C)
{
    csv_init();

    char line[512];
    if (!fgets(line, sizeof(line), s_csv)) {
        /* End of file: freeze at the last reading so the autosequence can
         * finish its current phase (e.g. land-detection) cleanly.         */
        fprintf(stderr, "[SIM] WARNING: CSV exhausted – repeating last row\n");
        /* s_row already holds the last values; just leave s_sim_time_ms as-is */
        goto fill_outputs;
    }

    {
        unsigned ts;
        int n = sscanf(line,
            "%u,"
            "%f,%f,"
            "%f,%f,"
            "%f,%f,%f,%f,%f,%f,"
            "%f,%f,%f,%f,%f,%f",
            &ts,
            &s_row.bar1,  &s_row.bar2,
            &s_row.bt1,   &s_row.bt2,
            &s_row.xl1_x, &s_row.xl1_y, &s_row.xl1_z,
            &s_row.w1_x,  &s_row.w1_y,  &s_row.w1_z,
            &s_row.xl2_x, &s_row.xl2_y, &s_row.xl2_z,
            &s_row.w2_x,  &s_row.w2_y,  &s_row.w2_z);

        if (n != 17) {
            fprintf(stderr, "[SIM] ERROR: malformed CSV row (parsed %d/17 fields): %s\n",
                    n, line);
            exit(EXIT_FAILURE);
        }

        s_sim_time_ms = (uint32_t)ts;
    }

fill_outputs:
    *bar1_hPa    = s_row.bar1;
    *bar2_hPa    = s_row.bar2;
    *bar1_temp_C = s_row.bt1;
    *bar2_temp_C = s_row.bt2;

    imu1->XL_x = s_row.xl1_x;
    imu1->XL_y = s_row.xl1_y;
    imu1->XL_z = s_row.xl1_z;
    imu1->W_x  = s_row.w1_x;
    imu1->W_y  = s_row.w1_y;
    imu1->W_z  = s_row.w1_z;

    imu2->XL_x = s_row.xl2_x;
    imu2->XL_y = s_row.xl2_y;
    imu2->XL_z = s_row.xl2_z;
    imu2->W_x  = s_row.w2_x;
    imu2->W_y  = s_row.w2_y;
    imu2->W_z  = s_row.w2_z;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Abort / arming
 * ═══════════════════════════════════════════════════════════════════════════ */
int should_abort(void)
{
    return 0;   /* no abort injected in simulation */
}

int valves_open(void)
{
    if (s_sim_time_ms >= VALVES_OPEN_SIM_MS) {
        if (!s_ignited) {
            /* Record the absolute sim-time so Fluctus offsets are correct. */
            s_ignited    = 1;
            s_ignition_ms = s_sim_time_ms;
            printf("[SIM] t=%6.3f s │ IGNITION – valves open\n",
                   s_sim_time_ms / 1000.0);
        }
        return 1;
    }
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Deployment channels  (one-shot: print once, then silently re-assert)
 * ═══════════════════════════════════════════════════════════════════════════ */
void deployPilot(void)
{
    if (!s_pilot_fired) {
        s_pilot_fired = 1;
        printf("[SIM] t=%6.3f s │ *** PILOT CHUTE DEPLOYED ***\n",
               s_sim_time_ms / 1000.0);
    }
}

void deployDrogue(void)
{
    if (!s_drogue_fired) {
        s_drogue_fired = 1;
        printf("[SIM] t=%6.3f s │ *** DROGUE DEPLOYED ***\n",
               s_sim_time_ms / 1000.0);
    }
}

void deployMain(void)
{
    if (!s_main_fired) {
        s_main_fired = 1;
        printf("[SIM] t=%6.3f s │ *** MAIN CHUTE DEPLOYED ***\n",
               s_sim_time_ms / 1000.0);
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Fluctus FC discrete outputs
 *
 * Each function returns 1 once the simulated Fluctus has "broadcast" its
 * detection.  Offsets are relative to ignition and match the CSV profile
 * computed by generate_flight_data.py.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Helper: ms elapsed since ignition (0 if not yet ignited). */
static uint32_t flight_ms(void)
{
    if (!s_ignited) return 0U;
    return s_sim_time_ms - s_ignition_ms;
}

uint8_t get_fluctus_apogee(void)
{
    return (flight_ms() >= FLUCTUS_APOGEE_FLIGHT_MS) ? 1U : 0U;
}

uint8_t get_fluctus_5k(void)
{
    return /*(flight_ms() >= FLUCTUS_5K_FLIGHT_MS) ? 1U :*/ 0U;
}

uint8_t get_fluctus_1k(void)
{
    return /*(flight_ms() >= FLUCTUS_1K_FLIGHT_MS) ? 1U : */0U;
}